# Site settings
title: suejarman.co.uk
email: your-email@domain.com
description: "Sue has worked as a freelance designer and art and design lecturer for 15 years, producing illustration, graphics, photography and surface design for a range of clients in fashion, publishing, interiors and travel."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: sue_jarman
github_username:  suejarman

# Build settings
markdown: kramdown
permalink: pretty
