# Site settings
title: suejarman.co.uk
email: sue@suejarman.co.uk
url: "http://suejarman.co.uk"
twitter_username: sue_jarman
github_username:  suejarman
copyright_owner: Sue Jarman

# Build settings
markdown: kramdown
permalink: pretty

collections:
  galleries:
    output: true